-- ============================================================
--  DAVE_SMILEYS_WORK_ORDERS
--  01_create_database.sql
--  Creates database, all tables, and foreign key constraints
-- ============================================================

DROP DATABASE IF EXISTS DAVE_SMILEYS_WORK_ORDERS;
CREATE DATABASE DAVE_SMILEYS_WORK_ORDERS;
USE DAVE_SMILEYS_WORK_ORDERS;

-- ============================================================
--  TABLES
-- ============================================================

CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    CONTACT_NAME VARCHAR(100),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    IS_ACTIVE TINYINT(1) DEFAULT 1
);

CREATE TABLE SERVICE_LOCATION (
    SERVICE_LOCATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    ADDRESS_LINE1 VARCHAR(150) NOT NULL,
    ADDRESS_LINE2 VARCHAR(150),
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    ZIP VARCHAR(10) NOT NULL,
    IS_ACTIVE TINYINT(1) DEFAULT 1
);

CREATE TABLE TECHNICIAN (
    TECHNICIAN_ID INT AUTO_INCREMENT PRIMARY KEY,
    TECHNICIAN_NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    IS_ACTIVE TINYINT(1) DEFAULT 1
);

CREATE TABLE WORK_ORDER (
    WORK_ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    SERVICE_LOCATION_ID INT NOT NULL,
    TECHNICIAN_ID INT NOT NULL,
    REQUESTED_DATE DATE NOT NULL,
    DATE_COMPLETED DATE,
    STATUS VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255)
);

CREATE TABLE PART (
    PART_ID INT AUTO_INCREMENT PRIMARY KEY,
    PART_NAME VARCHAR(100) NOT NULL,
    PART_DESCRIPTION VARCHAR(255),
    UNIT_COST DECIMAL(10,2) NOT NULL
);

CREATE TABLE WORK_ORDER_PART (
    WORK_ORDER_PART_ID INT AUTO_INCREMENT PRIMARY KEY,
    WORK_ORDER_ID INT NOT NULL,
    PART_ID INT NOT NULL,
    QUANTITY INT NOT NULL
);

CREATE TABLE WORK_ORDER_BILLING (
    BILLING_ID INT AUTO_INCREMENT PRIMARY KEY,
    WORK_ORDER_ID INT NOT NULL,
    LABOR_HOURS DECIMAL(10,2) NOT NULL,
    LABOR_RATE DECIMAL(10,2) NOT NULL,
    MISC_COST DECIMAL(10,2) DEFAULT 0
);

-- ============================================================
--  FOREIGN KEYS
-- ============================================================

ALTER TABLE SERVICE_LOCATION
    ADD CONSTRAINT FK_SERVICE_LOCATION_CUSTOMER_ID
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);

ALTER TABLE WORK_ORDER
    ADD CONSTRAINT FK_WORK_ORDER_CUSTOMER_ID
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);

ALTER TABLE WORK_ORDER
    ADD CONSTRAINT FK_WORK_ORDER_SERVICE_LOCATION_ID
    FOREIGN KEY (SERVICE_LOCATION_ID) REFERENCES SERVICE_LOCATION (SERVICE_LOCATION_ID);

ALTER TABLE WORK_ORDER
    ADD CONSTRAINT FK_WORK_ORDER_TECHNICIAN_ID
    FOREIGN KEY (TECHNICIAN_ID) REFERENCES TECHNICIAN (TECHNICIAN_ID);

ALTER TABLE WORK_ORDER_PART
    ADD CONSTRAINT FK_WORK_ORDER_PART_WORK_ORDER_ID
    FOREIGN KEY (WORK_ORDER_ID) REFERENCES WORK_ORDER (WORK_ORDER_ID);

ALTER TABLE WORK_ORDER_PART
    ADD CONSTRAINT FK_WORK_ORDER_PART_PART_ID
    FOREIGN KEY (PART_ID) REFERENCES PART (PART_ID);

ALTER TABLE WORK_ORDER_BILLING
    ADD CONSTRAINT FK_WORK_ORDER_BILLING_WORK_ORDER_ID
    FOREIGN KEY (WORK_ORDER_ID) REFERENCES WORK_ORDER (WORK_ORDER_ID);
