-- ============================================================
--  DAVE_SMILEYS_WORK_ORDERS
--  03_views.sql
--  All QRY_ and RPT_ views
-- ============================================================

USE DAVE_SMILEYS_WORK_ORDERS;

CREATE VIEW QRY_WORK_ORDER_DETAILS AS
SELECT
    WO.WORK_ORDER_ID,
    C.CUSTOMER_NAME,
    SL.ADDRESS_LINE1,
    SL.CITY,
    SL.STATE,
    T.TECHNICIAN_NAME,
    WO.REQUESTED_DATE,
    WO.DATE_COMPLETED,
    WO.STATUS,
    WO.DESCRIPTION
FROM WORK_ORDER WO
JOIN CUSTOMER C ON WO.CUSTOMER_ID = C.CUSTOMER_ID
JOIN SERVICE_LOCATION SL ON WO.SERVICE_LOCATION_ID = SL.SERVICE_LOCATION_ID
JOIN TECHNICIAN T ON WO.TECHNICIAN_ID = T.TECHNICIAN_ID;

CREATE VIEW QRY_WORK_ORDER_PARTS_USED AS
SELECT
    WOP.WORK_ORDER_ID,
    P.PART_NAME,
    WOP.QUANTITY,
    P.UNIT_COST,
    (WOP.QUANTITY * P.UNIT_COST) AS TOTAL_COST
FROM WORK_ORDER_PART WOP
JOIN PART P ON WOP.PART_ID = P.PART_ID;

CREATE VIEW QRY_WORK_ORDER_BILLING_SUMMARY AS
SELECT
    B.WORK_ORDER_ID,
    B.LABOR_HOURS,
    B.LABOR_RATE,
    (B.LABOR_HOURS * B.LABOR_RATE) AS LABOR_TOTAL,
    B.MISC_COST
FROM WORK_ORDER_BILLING B;

CREATE VIEW RPT_WORK_ORDER_REPORT AS
SELECT
    D.WORK_ORDER_ID,
    D.CUSTOMER_NAME,
    D.ADDRESS_LINE1,
    D.CITY,
    D.STATE,
    D.TECHNICIAN_NAME,
    D.REQUESTED_DATE,
    D.DATE_COMPLETED,
    D.STATUS,
    D.DESCRIPTION,
    COALESCE(SUM(PU.TOTAL_COST), 0) AS PARTS_TOTAL,
    COALESCE(BS.LABOR_TOTAL, 0) AS LABOR_TOTAL,
    COALESCE(BS.MISC_COST, 0) AS MISC_TOTAL,
    COALESCE(SUM(PU.TOTAL_COST), 0) +
    COALESCE(BS.LABOR_TOTAL, 0) +
    COALESCE(BS.MISC_COST, 0) AS GRAND_TOTAL
FROM QRY_WORK_ORDER_DETAILS D
LEFT JOIN QRY_WORK_ORDER_PARTS_USED PU ON D.WORK_ORDER_ID = PU.WORK_ORDER_ID
LEFT JOIN QRY_WORK_ORDER_BILLING_SUMMARY BS ON D.WORK_ORDER_ID = BS.WORK_ORDER_ID
GROUP BY
    D.WORK_ORDER_ID,
    D.CUSTOMER_NAME,
    D.ADDRESS_LINE1,
    D.CITY,
    D.STATE,
    D.TECHNICIAN_NAME,
    D.REQUESTED_DATE,
    D.DATE_COMPLETED,
    D.STATUS,
    D.DESCRIPTION,
    BS.LABOR_TOTAL,
    BS.MISC_COST;
